CREATE DATABASE IF NOT EXISTS TEST;
USE TEST;

DROP TABLE USER_INFO;
DROP TABLE ADD_TABLE;
DROP TABLE ADD_ITEM;
DROP TABLE ORDER_ITEM;
DROP TABLE BILL_ORDER;
DROP TABLE ADDRESS_TABLE;

CREATE TABLE IF NOT EXISTS USER_INFO
(USERNAME VARCHAR(50) PRIMARY KEY, PASSWORD VARCHAR(32) NOT NULL, ROLE INT(2)); 

INSERT INTO USER_INFO(USERNAME,PASSWORD,ROLE) VALUES('ADMIN',MD5('ADMIN'),2);

CREATE TABLE IF NOT EXISTS ADD_TABLE(
SNO INT(11) NOT NULL AUTO_INCREMENT,
TNAME VARCHAR(10) NOT NULL, 
STA VARCHAR(10) NOT NULL,
CREATED DATETIME NOT NULL,
MODIFIED DATETIME NOT NULL,
PRIMARY KEY (SNO),
UNIQUE KEY IKEY (TNAME)
);





CREATE TABLE IF NOT EXISTS ADD_ITEM(
SNO INT(11) NOT NULL AUTO_INCREMENT,
ITEM VARCHAR(100) NOT NULL, 
RATE VARCHAR(10) NOT NULL,
CREATED DATETIME NOT NULL,
MODIFIED DATETIME NOT NULL,
PRIMARY KEY (SNO),
UNIQUE KEY IKEY (ITEM)
);


CREATE TABLE IF NOT EXISTS ORDER_ITEM(
SNO INT(11) NOT NULL AUTO_INCREMENT,
TNAME VARCHAR(10) NOT NULL, 
ITEM VARCHAR(100) NOT NULL, 
QTY VARCHAR(7) NOT NULL, 
RATE VARCHAR(10) NOT NULL,
AMT VARCHAR(10) NOT NULL,
STA VARCHAR(6) NOT NULL,
INVOICE VARCHAR(10) NOT NULL,
CREATED DATETIME NOT NULL,
MODIFIED DATETIME NOT NULL,
PRIMARY KEY (SNO)
);


CREATE TABLE IF NOT EXISTS BILL_ORDER(
FNO INT(11) NOT NULL,
TNAME VARCHAR(10) NOT NULL, 
TAXVAL VARCHAR(20) NOT NULL, 
CGST VARCHAR(3) NOT NULL, 
SGST VARCHAR(10) NOT NULL,
DISCP VARCHAR(10) NOT NULL,
DISCA VARCHAR(10) NOT NULL,
MODEP VARCHAR(4) NOT NULL,
TOTALAMT VARCHAR(10) NOT NULL,
CREATED DATETIME NOT NULL,
MODIFIED DATETIME NOT NULL,
PRIMARY KEY (FNO)
);

CREATE TABLE IF NOT EXISTS ADDRESS_TABLE(
SNO INT(11) NOT NULL AUTO_INCREMENT,
ADDRESS1 VARCHAR(50) NOT NULL,
ADDRESS2 VARCHAR(50) NOT NULL,
ADDRESS3 VARCHAR(50) NOT NULL,
ADDRESS4 VARCHAR(50) NOT NULL,
ADDRESS5 VARCHAR(50),
GST VARCHAR(30) NOT NULL,
WEB VARCHAR(50),
EMAIL VARCHAR(50),
MOB VARCHAR(100),
FB VARCHAR(50),
INSTA VARCHAR(50),
TWIT VARCHAR(50),
PRIMARY KEY (SNO)
);


INSERT INTO order_item(tname,item,qty,rate,amt,sta,invoice,created,modified) values ('ALL','ALL','1','1','1','PAID','ALL',NOW(),NOW());









INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Mix veg scezwan roll','29',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Egg fried roll','29',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Veg fried roll','29',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Crispy veg sandwich','34',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Veg struddle','24',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Veg Puff','9',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Egg Puff','14',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Vegetale mirch chatak','14',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Paneer Frankie Roll','34',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Mushroom Cheese Roll','39',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Pineapple  pastry','49',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Blackforest pastry','54',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Caramello pastry','59',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Pista chocolate pastry','74',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Choco vanilla pastry','74',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Raspberry chocolate pastry','74',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Classic redvelvet pastry','74',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Litchi butterscoth pastry','64',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Strawberry pastry','64',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Choco truffle pastry','64',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Choco fantasy pastry','69',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Milky pastry','89',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('American brownie','59',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Apple pie','64',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Mud pie','49',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Chocolate  mousse','49',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Vanila  mousse','49',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Strawberry  mousse','49',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Pineapple  mousse','49',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Chocolate  souffle','49',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Strawberry  souffle','49',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Mango  souffle','49',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Pista','49',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Redvelvet  souffle','49',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Fresh fruit tart','34',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Chocolate tart','34',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Jackfruit tart','39',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Fudge tart','39',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Veg pizza small','49',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Panner  pizza  small','59',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Mushroom pizza  small','59',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Veg pizza large','74',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Panner  pizza  large','79',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Mushroom pizza  large','79',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Egg sandwich','49',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Egg sandwich cheese','79',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Veg grilled sandwich','39',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Veg grilled sandwich with cheese','54',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Panner cheese sandwich','69',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('VEG BURGER','39',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('VEG cheese burger','54',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Chef special burger','69',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Aloo tikki burger','39',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('King burger','74',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Finger chips','49',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Potato pops','39',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Vegetable nuggets','49',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Moosy mess','79',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Bottoms up brownie','79',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Cheery mania','79',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Peanut butter bomb','84',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('COCONUT extreme','119',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Fruity crunch punch','79',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Rose falooda','79',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Arabian faloda','129',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('CLASSIC Falooda','124',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Kulfi  falooda','119',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Strawbeery falooda','99',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Mango falooda','99',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Fruit ice cream','54',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Gud bud','79',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Tropical fruit Sunday','99',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Magic banana','129',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('White chocolate sundae','99',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('American brownie with ice cream','119',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Apple pie with ice cream','99',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Mud pie with ice cream','74',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Sticky pudding','59',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Choco fantasy ice cream','109',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Caramel custard','49',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('DBC sunde ice cream cake','119',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('BLACKFOREST ice cream cake','114',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('REDVELVET ice cream cake','124',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Choco vanilla ice cream cake','99',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Vanila ice cream cake','99',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Chocolate ice cream cake','99',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Vanila cups/corn','35',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Chocolate cups/corn','40',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Strawberry cups/corn','40',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Mango cups/corn','35',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Butterscotch cups/corn','40',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Pista cups/corn','40',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Blackcurrent cups/corn','40',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Spanish delight cups/corn','55',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Choco chips cups/corn','50',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Arabian delight cups/corn','60',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Kulfi cups/corn','50',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Tender coconut cups/corn','60',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Jackfruit cups/corn','60',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Mosambi  juice','29',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Watermelon  juice','29',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Orange juice','34',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Muskmelon juice','29',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Grape juice','29',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Pulpy Grape juice','34',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Anar juice','49',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Apple juice','49',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Pineapple juice','34',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Fresh lime juice','19',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Mango juice','34',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Strawberry (seasonal) juice','64',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Apple milkshake','59',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('ANAR  milkshake','64',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('CHIKKU  milkshake','49',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('MUSKMELON milkshake','44',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Mango milkshake','54',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('STRAWBERRY  milkshake','64',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('KIWI milkshake','79',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Badam milkshake','49',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Sharja milkshake','49',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Tendercoconut milkshake','59',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Mixed dry fruits  milkshake','99',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Almod  dryfruit milkshake','99',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Anjeer milkshake','89',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Vanila  ice cream shake','74',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Chocolate ice cream shake','79',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Strawberry ice cream shake','74',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Mango ice cream shake','74',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Butterscotch ice cream shake','79',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Pista ice cream shake','74',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Blackcurrent ice cream shake','84',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Spanish delight ice cream shake','84',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Choco chips ice cream shake','79',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Arabian delight ice cream shake','89',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Kulfi ice cream shake','89',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Tendercoconut ice cream shake','89',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Jackfruit ice cream shake','89',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('REDVELVET special shake','89',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('BROWNIE special shake','89',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('COOKIES special shake','89',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Apple with vanilla shake + ice cream','99',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Chikku with vanilla shake + ice cream','99',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Anar with vanilla shake + ice cream','99',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Mango vanilla shake + ice cream','99',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('FRESH LIME soda','29',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('MINT LIME soda','34',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('GINGER LIME  soda','34',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Classic lime soda','34',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Panipuri','29',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Masala puri','29',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Dahi puri','39',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Dahi masala','39',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Sev puri','39',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Sukka puri','29',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Bhel puri','29',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Tea','10',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Coffe','15',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Hotchocolate','20',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Horlicks','15',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Badam milk','15',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Lemon  ice tea','49',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Mint ice tea','49',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Strawberry  ice tea','49',NOW(),NOW());
INSERT INTO ADD_ITEM(ITEM,RATE,CREATED,MODIFIED) VALUES('Mango ice tea','49',NOW(),NOW());

